// Code generated by protoc-gen-go. DO NOT EDIT.
// source: ticktick.proto

/*
Package pb is a generated protocol buffer package.

It is generated from these files:
	ticktick.proto

It has these top-level messages:
	TickTickMessage
	ReadMessagesRequest
*/
package pb

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type TickTickMessage struct {
	Message string `protobuf:"bytes,1,opt,name=message" json:"message,omitempty"`
}

func (m *TickTickMessage) Reset()                    { *m = TickTickMessage{} }
func (m *TickTickMessage) String() string            { return proto.CompactTextString(m) }
func (*TickTickMessage) ProtoMessage()               {}
func (*TickTickMessage) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *TickTickMessage) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

type ReadMessagesRequest struct {
}

func (m *ReadMessagesRequest) Reset()                    { *m = ReadMessagesRequest{} }
func (m *ReadMessagesRequest) String() string            { return proto.CompactTextString(m) }
func (*ReadMessagesRequest) ProtoMessage()               {}
func (*ReadMessagesRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func init() {
	proto.RegisterType((*TickTickMessage)(nil), "ticktick.pb.TickTickMessage")
	proto.RegisterType((*ReadMessagesRequest)(nil), "ticktick.pb.ReadMessagesRequest")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for TickTick service

type TickTickClient interface {
	GetMessages(ctx context.Context, in *ReadMessagesRequest, opts ...grpc.CallOption) (TickTick_GetMessagesClient, error)
}

type tickTickClient struct {
	cc *grpc.ClientConn
}

func NewTickTickClient(cc *grpc.ClientConn) TickTickClient {
	return &tickTickClient{cc}
}

func (c *tickTickClient) GetMessages(ctx context.Context, in *ReadMessagesRequest, opts ...grpc.CallOption) (TickTick_GetMessagesClient, error) {
	stream, err := grpc.NewClientStream(ctx, &_TickTick_serviceDesc.Streams[0], c.cc, "/ticktick.pb.TickTick/GetMessages", opts...)
	if err != nil {
		return nil, err
	}
	x := &tickTickGetMessagesClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type TickTick_GetMessagesClient interface {
	Recv() (*TickTickMessage, error)
	grpc.ClientStream
}

type tickTickGetMessagesClient struct {
	grpc.ClientStream
}

func (x *tickTickGetMessagesClient) Recv() (*TickTickMessage, error) {
	m := new(TickTickMessage)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// Server API for TickTick service

type TickTickServer interface {
	GetMessages(*ReadMessagesRequest, TickTick_GetMessagesServer) error
}

func RegisterTickTickServer(s *grpc.Server, srv TickTickServer) {
	s.RegisterService(&_TickTick_serviceDesc, srv)
}

func _TickTick_GetMessages_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ReadMessagesRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(TickTickServer).GetMessages(m, &tickTickGetMessagesServer{stream})
}

type TickTick_GetMessagesServer interface {
	Send(*TickTickMessage) error
	grpc.ServerStream
}

type tickTickGetMessagesServer struct {
	grpc.ServerStream
}

func (x *tickTickGetMessagesServer) Send(m *TickTickMessage) error {
	return x.ServerStream.SendMsg(m)
}

var _TickTick_serviceDesc = grpc.ServiceDesc{
	ServiceName: "ticktick.pb.TickTick",
	HandlerType: (*TickTickServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "GetMessages",
			Handler:       _TickTick_GetMessages_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "ticktick.proto",
}

func init() { proto.RegisterFile("ticktick.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 138 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x2b, 0xc9, 0x4c, 0xce,
	0x06, 0x61, 0xbd, 0x82, 0xa2, 0xfc, 0x92, 0x7c, 0x21, 0x6e, 0x04, 0x3f, 0x49, 0x49, 0x9b, 0x8b,
	0x3f, 0x24, 0x33, 0x39, 0x1b, 0x84, 0x7d, 0x53, 0x8b, 0x8b, 0x13, 0xd3, 0x53, 0x85, 0x24, 0xb8,
	0xd8, 0x73, 0x21, 0x4c, 0x09, 0x46, 0x05, 0x46, 0x0d, 0xce, 0x20, 0x18, 0x57, 0x49, 0x94, 0x4b,
	0x38, 0x28, 0x35, 0x31, 0x05, 0xaa, 0xb0, 0x38, 0x28, 0xb5, 0xb0, 0x34, 0xb5, 0xb8, 0xc4, 0x28,
	0x96, 0x8b, 0x03, 0x66, 0x86, 0x50, 0x20, 0x17, 0xb7, 0x7b, 0x6a, 0x09, 0x4c, 0x85, 0x90, 0x82,
	0x1e, 0x92, 0x65, 0x7a, 0x58, 0x34, 0x4b, 0xc9, 0xa0, 0xa8, 0x40, 0x73, 0x8b, 0x12, 0x83, 0x01,
	0xa3, 0x13, 0x4b, 0x14, 0x53, 0x41, 0x52, 0x12, 0x1b, 0xd8, 0xf1, 0xc6, 0x80, 0x00, 0x00, 0x00,
	0xff, 0xff, 0x1e, 0x27, 0x53, 0x6b, 0xce, 0x00, 0x00, 0x00,
}
